import keyMirror from 'keymirror';

export default keyMirror({
  REGISTER_FAILURE: null,
  REGISTER_START: null,
  REGISTER_SUCCESS: null,

  REQUEST_PASSWORD_RESET_FAILURE: null,
  REQUEST_PASSWORD_RESET_START: null,
  REQUEST_PASSWORD_RESET_SUCCESS: null,

  RESET_PASSWORD_FAILURE: null,
  RESET_PASSWORD_START: null,
  RESET_PASSWORD_SUCCESS: null,

  SIGN_IN_START: null,
  SIGN_IN_SUCCESS: null,
  SIGN_IN_FAILURE: null,

  SIGN_OUT: null,

  UPDATE_TOKEN_INFO: null
});
